service: contact-me

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.secrets.ENV}
  region: "us-east-1"
  environment:
    EMAIL: ${self:custom.secrets.EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogStream
        - logs:CreateLogGroup
        - logs:PutLogEvents
      Resource: "*"

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: contact-me
          method: POST
          cors: true
